version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    links:
      - php

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app:/app
      - ./logs/nginx:/var/log/nginx/
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - php-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
    volumes:
      - ./app:/app
      -  ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - php-network


  mysql:
    image: mysql:5.7
    ports:
    - "${MYSQL_PORT}:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: itaQmtXh
      MYSQL_DATABASE: test_db
    volumes:
      - ./db:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
#      - ./data:/docker-entrypoint-initdb.d
      - ./school.sql:/school.sql
    networks:
      - php-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: itaQmtXh
      PMA_HOST: mysql
      UPLOAD_LIMIT: 1G
      PMA_ARBITRARY: 1
    links:
      - mysql
    networks:
      - php-network


networks:
  php-network:
    driver: bridge


volumes:
  db: {}